package com.creapption.sri.authorization;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by Apache CXF 3.4.4
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "http://ec.gob.sri.ws.autorizacion", name = "AutorizacionComprobantesOffline")
@XmlSeeAlso({ObjectFactory.class})
public interface AutorizacionComprobantesOffline {

    @WebMethod
    @RequestWrapper(localName = "autorizacionComprobante", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "com.creapption.sri.authorization.AutorizacionComprobante")
    @ResponseWrapper(localName = "autorizacionComprobanteResponse", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "com.creapption.sri.authorization.AutorizacionComprobanteResponse")
    @WebResult(name = "RespuestaAutorizacionComprobante", targetNamespace = "")
    public RespuestaComprobante autorizacionComprobante(

        @WebParam(name = "claveAccesoComprobante", targetNamespace = "")
        String claveAccesoComprobante
    );

    @WebMethod
    @RequestWrapper(localName = "autorizacionComprobanteLote", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "com.creapption.sri.authorization.AutorizacionComprobanteLote")
    @ResponseWrapper(localName = "autorizacionComprobanteLoteResponse", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "com.creapption.sri.authorization.AutorizacionComprobanteLoteResponse")
    @WebResult(name = "RespuestaAutorizacionLote", targetNamespace = "")
    public RespuestaLote autorizacionComprobanteLote(

        @WebParam(name = "claveAccesoLote", targetNamespace = "")
        String claveAccesoLote
    );
}
